import { Track, Artist, Album, Playlist, Category } from '@/types';

export function formatDuration(seconds: number): string {
  const minutes = Math.floor(seconds / 60);
  const remainingSeconds = Math.floor(seconds % 60);
  return `${minutes}:${remainingSeconds.toString().padStart(2, '0')}`;
}

export function formatNumber(num: number): string {
  if (num >= 1_000_000) {
    return `${(num / 1_000_000).toFixed(1)}M`;
  }
  if (num >= 1_000) {
    return `${(num / 1_000).toFixed(1)}K`;
  }
  return num.toString();
}

export function formatFollowers(num: number): string {
  return new Intl.NumberFormat('en-US').format(num);
}

export function cn(...classes: (string | undefined | null | false)[]): string {
  return classes.filter(Boolean).join(' ');
}

export const SAMPLE_TRACKS: Track[] = [
  {
    id: 'track-1',
    title: 'Blinding Lights',
    artist: 'The Weeknd',
    artistId: 'artist-1',
    album: 'After Hours',
    albumId: 'album-1',
    duration: 200,
    coverUrl: 'https://picsum.photos/seed/track1/300/300',
    explicit: false,
    popularity: 98,
  },
  {
    id: 'track-2',
    title: 'Save Your Tears',
    artist: 'The Weeknd',
    artistId: 'artist-1',
    album: 'After Hours',
    albumId: 'album-1',
    duration: 215,
    coverUrl: 'https://picsum.photos/seed/track2/300/300',
    explicit: false,
    popularity: 95,
  },
  {
    id: 'track-3',
    title: 'Levitating',
    artist: 'Dua Lipa',
    artistId: 'artist-2',
    album: 'Future Nostalgia',
    albumId: 'album-2',
    duration: 203,
    coverUrl: 'https://picsum.photos/seed/track3/300/300',
    explicit: false,
    popularity: 94,
  },
  {
    id: 'track-4',
    title: 'Don\'t Start Now',
    artist: 'Dua Lipa',
    artistId: 'artist-2',
    album: 'Future Nostalgia',
    albumId: 'album-2',
    duration: 183,
    coverUrl: 'https://picsum.photos/seed/track4/300/300',
    explicit: false,
    popularity: 93,
  },
  {
    id: 'track-5',
    title: 'drivers license',
    artist: 'Olivia Rodrigo',
    artistId: 'artist-3',
    album: 'SOUR',
    albumId: 'album-3',
    duration: 242,
    coverUrl: 'https://picsum.photos/seed/track5/300/300',
    explicit: false,
    popularity: 96,
  },
  {
    id: 'track-6',
    title: 'good 4 u',
    artist: 'Olivia Rodrigo',
    artistId: 'artist-3',
    album: 'SOUR',
    albumId: 'album-3',
    duration: 178,
    coverUrl: 'https://picsum.photos/seed/track6/300/300',
    explicit: true,
    popularity: 95,
  },
  {
    id: 'track-7',
    title: 'Peaches',
    artist: 'Justin Bieber',
    artistId: 'artist-4',
    album: 'Justice',
    albumId: 'album-4',
    duration: 198,
    coverUrl: 'https://picsum.photos/seed/track7/300/300',
    explicit: true,
    popularity: 91,
  },
  {
    id: 'track-8',
    title: 'Stay',
    artist: 'The Kid LAROI & Justin Bieber',
    artistId: 'artist-4',
    album: 'F*CK LOVE 3',
    albumId: 'album-5',
    duration: 141,
    coverUrl: 'https://picsum.photos/seed/track8/300/300',
    explicit: true,
    popularity: 97,
  },
  {
    id: 'track-9',
    title: 'Montero (Call Me By Your Name)',
    artist: 'Lil Nas X',
    artistId: 'artist-5',
    album: 'MONTERO',
    albumId: 'album-6',
    duration: 137,
    coverUrl: 'https://picsum.photos/seed/track9/300/300',
    explicit: true,
    popularity: 94,
  },
  {
    id: 'track-10',
    title: 'Industry Baby',
    artist: 'Lil Nas X & Jack Harlow',
    artistId: 'artist-5',
    album: 'MONTERO',
    albumId: 'album-6',
    duration: 212,
    coverUrl: 'https://picsum.photos/seed/track10/300/300',
    explicit: true,
    popularity: 93,
  },
  {
    id: 'track-11',
    title: 'Heat Waves',
    artist: 'Glass Animals',
    artistId: 'artist-6',
    album: 'Dreamland',
    albumId: 'album-7',
    duration: 238,
    coverUrl: 'https://picsum.photos/seed/track11/300/300',
    explicit: false,
    popularity: 96,
  },
  {
    id: 'track-12',
    title: 'Easy On Me',
    artist: 'Adele',
    artistId: 'artist-7',
    album: '30',
    albumId: 'album-8',
    duration: 224,
    coverUrl: 'https://picsum.photos/seed/track12/300/300',
    explicit: false,
    popularity: 97,
  },
];

export const SAMPLE_ARTISTS: Artist[] = [
  {
    id: 'artist-1',
    name: 'The Weeknd',
    imageUrl: 'https://picsum.photos/seed/artist1/400/400',
    genres: ['R&B', 'Pop', 'Alternative R&B'],
    monthlyListeners: 85_000_000,
    bio: 'Abel Makkonen Tesfaye, known professionally as The Weeknd, is a Canadian singer, songwriter, and record producer. He is known for his sonic versatility and dark lyricism, with his music exploring escapism, romance, and melancholia.',
    topTracks: SAMPLE_TRACKS.filter(t => t.artistId === 'artist-1'),
    albums: [],
    verified: true,
  },
  {
    id: 'artist-2',
    name: 'Dua Lipa',
    imageUrl: 'https://picsum.photos/seed/artist2/400/400',
    genres: ['Pop', 'Dance Pop', 'Electropop'],
    monthlyListeners: 72_000_000,
    bio: 'Dua Lipa is an English-Albanian singer and songwriter. After working as a model, she signed with a management company and began her music career. Her self-titled debut album was released in 2017, and her second studio album Future Nostalgia became a global phenomenon.',
    topTracks: SAMPLE_TRACKS.filter(t => t.artistId === 'artist-2'),
    albums: [],
    verified: true,
  },
  {
    id: 'artist-3',
    name: 'Olivia Rodrigo',
    imageUrl: 'https://picsum.photos/seed/artist3/400/400',
    genres: ['Pop', 'Pop Rock', 'Indie Pop'],
    monthlyListeners: 58_000_000,
    bio: 'Olivia Isabel Rodrigo is an American singer, songwriter, and actress. She began her career as a child actress, before releasing her debut single drivers license in January 2021, which broke multiple streaming records and reached number one in numerous countries.',
    topTracks: SAMPLE_TRACKS.filter(t => t.artistId === 'artist-3'),
    albums: [],
    verified: true,
  },
  {
    id: 'artist-4',
    name: 'Justin Bieber',
    imageUrl: 'https://picsum.photos/seed/artist4/400/400',
    genres: ['Pop', 'R&B', 'Dance Pop'],
    monthlyListeners: 68_000_000,
    bio: 'Justin Drew Bieber is a Canadian singer. He was discovered by talent manager Scooter Braun and signed with RBMG Records in 2008. Bieber\'s debut EP My World was released in November 2009 and certified platinum in the United States.',
    topTracks: SAMPLE_TRACKS.filter(t => t.artistId === 'artist-4'),
    albums: [],
    verified: true,
  },
  {
    id: 'artist-5',
    name: 'Lil Nas X',
    imageUrl: 'https://picsum.photos/seed/artist5/400/400',
    genres: ['Hip-Hop', 'Pop', 'Country Rap'],
    monthlyListeners: 42_000_000,
    bio: 'Montero Lamar Hill, known professionally as Lil Nas X, is an American rapper, singer, and songwriter. He rose to fame in 2019 with his country rap single Old Town Road, which became the longest-running number-one single on the Billboard Hot 100.',
    topTracks: SAMPLE_TRACKS.filter(t => t.artistId === 'artist-5'),
    albums: [],
    verified: true,
  },
  {
    id: 'artist-6',
    name: 'Glass Animals',
    imageUrl: 'https://picsum.photos/seed/artist6/400/400',
    genres: ['Indie Pop', 'Psychedelic Pop', 'Art Pop'],
    monthlyListeners: 28_000_000,
    bio: 'Glass Animals are a British indie pop band formed in Oxford in 2010. The band consists of Dave Bayley, Drew MacFarlane, Edmund Irwin-Singer, and Joe Seaward. Their third studio album Dreamland was released in 2020.',
    topTracks: SAMPLE_TRACKS.filter(t => t.artistId === 'artist-6'),
    albums: [],
    verified: true,
  },
];

export const SAMPLE_ALBUMS: Album[] = [
  {
    id: 'album-1',
    title: 'After Hours',
    artistId: 'artist-1',
    artist: 'The Weeknd',
    coverUrl: 'https://picsum.photos/seed/album1/300/300',
    releaseYear: 2020,
    tracks: SAMPLE_TRACKS.filter(t => t.albumId === 'album-1'),
    genre: 'R&B',
    type: 'album',
  },
  {
    id: 'album-2',
    title: 'Future Nostalgia',
    artistId: 'artist-2',
    artist: 'Dua Lipa',
    coverUrl: 'https://picsum.photos/seed/album2/300/300',
    releaseYear: 2020,
    tracks: SAMPLE_TRACKS.filter(t => t.albumId === 'album-2'),
    genre: 'Pop',
    type: 'album',
  },
  {
    id: 'album-3',
    title: 'SOUR',
    artistId: 'artist-3',
    artist: 'Olivia Rodrigo',
    coverUrl: 'https://picsum.photos/seed/album3/300/300',
    releaseYear: 2021,
    tracks: SAMPLE_TRACKS.filter(t => t.albumId === 'album-3'),
    genre: 'Pop Rock',
    type: 'album',
  },
  {
    id: 'album-4',
    title: 'Justice',
    artistId: 'artist-4',
    artist: 'Justin Bieber',
    coverUrl: 'https://picsum.photos/seed/album4/300/300',
    releaseYear: 2021,
    tracks: SAMPLE_TRACKS.filter(t => t.albumId === 'album-4'),
    genre: 'Pop',
    type: 'album',
  },
  {
    id: 'album-5',
    title: 'F*CK LOVE 3',
    artistId: 'artist-4',
    artist: 'The Kid LAROI',
    coverUrl: 'https://picsum.photos/seed/album5/300/300',
    releaseYear: 2021,
    tracks: SAMPLE_TRACKS.filter(t => t.albumId === 'album-5'),
    genre: 'Hip-Hop',
    type: 'album',
  },
  {
    id: 'album-6',
    title: 'MONTERO',
    artistId: 'artist-5',
    artist: 'Lil Nas X',
    coverUrl: 'https://picsum.photos/seed/album6/300/300',
    releaseYear: 2021,
    tracks: SAMPLE_TRACKS.filter(t => t.albumId === 'album-6'),
    genre: 'Hip-Hop',
    type: 'album',
  },
  {
    id: 'album-7',
    title: 'Dreamland',
    artistId: 'artist-6',
    artist: 'Glass Animals',
    coverUrl: 'https://picsum.photos/seed/album7/300/300',
    releaseYear: 2020,
    tracks: SAMPLE_TRACKS.filter(t => t.albumId === 'album-7'),
    genre: 'Indie Pop',
    type: 'album',
  },
  {
    id: 'album-8',
    title: '30',
    artistId: 'artist-7',
    artist: 'Adele',
    coverUrl: 'https://picsum.photos/seed/album8/300/300',
    releaseYear: 2021,
    tracks: SAMPLE_TRACKS.filter(t => t.albumId === 'album-8'),
    genre: 'Soul',
    type: 'album',
  },
];

export const SAMPLE_PLAYLISTS: Playlist[] = [
  {
    id: 'playlist-1',
    title: 'Today\'s Top Hits',
    description: 'Jung Kook is on top of the Hottest 50!',
    coverUrl: 'https://picsum.photos/seed/playlist1/300/300',
    owner: 'Spotify',
    tracks: SAMPLE_TRACKS.slice(0, 6),
    followers: 32_000_000,
    isPublic: true,
    createdAt: '2024-01-01',
  },
  {
    id: 'playlist-2',
    title: 'RapCaviar',
    description: 'New music from Drake, Travis Scott and more.',
    coverUrl: 'https://picsum.photos/seed/playlist2/300/300',
    owner: 'Spotify',
    tracks: SAMPLE_TRACKS.slice(6, 12),
    followers: 14_000_000,
    isPublic: true,
    createdAt: '2024-01-01',
  },
  {
    id: 'playlist-3',
    title: 'Chill Hits',
    description: 'Kick back to the best new and recent chill hits.',
    coverUrl: 'https://picsum.photos/seed/playlist3/300/300',
    owner: 'Spotify',
    tracks: SAMPLE_TRACKS.slice(2, 8),
    followers: 8_500_000,
    isPublic: true,
    createdAt: '2024-01-01',
  },
  {
    id: 'playlist-4',
    title: 'Mood Booster',
    description: 'Get happy with today\'s dose of feel-good songs!',
    coverUrl: 'https://picsum.photos/seed/playlist4/300/300',
    owner: 'Spotify',
    tracks: SAMPLE_TRACKS.slice(0, 8),
    followers: 11_000_000,
    isPublic: true,
    createdAt: '2024-01-01',
  },
  {
    id: 'playlist-5',
    title: 'Pop Rising',
    description: 'The future of pop is here.',
    coverUrl: 'https://picsum.photos/seed/playlist5/300/300',
    owner: 'Spotify',
    tracks: SAMPLE_TRACKS.slice(1, 7),
    followers: 5_200_000,
    isPublic: true,
    createdAt: '2024-01-01',
  },
  {
    id: 'playlist-6',
    title: 'Hot Country',
    description: 'The hottest country songs right now.',
    coverUrl: 'https://picsum.photos/seed/playlist6/300/300',
    owner: 'Spotify',
    tracks: SAMPLE_TRACKS.slice(3, 9),
    followers: 7_800_000,
    isPublic: true,
    createdAt: '2024-01-01',
  },
  {
    id: 'playlist-7',
    title: 'Peaceful Piano',
    description: 'Relax and indulge with beautiful piano pieces.',
    coverUrl: 'https://picsum.photos/seed/playlist7/300/300',
    owner: 'Spotify',
    tracks: SAMPLE_TRACKS.slice(4, 10),
    followers: 9_100_000,
    isPublic: true,
    createdAt: '2024-01-01',
  },
  {
    id: 'playlist-8',
    title: 'Workout Beats',
    description: 'High energy tracks to fuel your workout.',
    coverUrl: 'https://picsum.photos/seed/playlist8/300/300',
    owner: 'Spotify',
    tracks: SAMPLE_TRACKS.slice(5, 11),
    followers: 6_300_000,
    isPublic: true,
    createdAt: '2024-01-01',
  },
];

export const SAMPLE_CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Pop', imageUrl: 'https://picsum.photos/seed/cat1/200/200', color: '#E91429' },
  { id: 'cat-2', name: 'Hip-Hop', imageUrl: 'https://picsum.photos/seed/cat2/200/200', color: '#509BF5' },
  { id: 'cat-3', name: 'R&B', imageUrl: 'https://picsum.photos/seed/cat3/200/200', color: '#E8115B' },
  { id: 'cat-4', name: 'Rock', imageUrl: 'https://picsum.photos/seed/cat4/200/200', color: '#BA5D07' },
  { id: 'cat-5', name: 'Electronic', imageUrl: 'https://picsum.photos/seed/cat5/200/200', color: '#1E3264' },
  { id: 'cat-6', name: 'Country', imageUrl: 'https://picsum.photos/seed/cat6/200/200', color: '#8D67AB' },
  { id: 'cat-7', name: 'Jazz', imageUrl: 'https://picsum.photos/seed/cat7/200/200', color: '#148A08' },
  { id: 'cat-8', name: 'Classical', imageUrl: 'https://picsum.photos/seed/cat8/200/200', color: '#E61E32' },
  { id: 'cat-9', name: 'Latin', imageUrl: 'https://picsum.photos/seed/cat9/200/200', color: '#DC148C' },
  { id: 'cat-10', name: 'Indie', imageUrl: 'https://picsum.photos/seed/cat10/200/200', color: '#477D95' },
  { id: 'cat-11', name: 'Metal', imageUrl: 'https://picsum.photos/seed/cat11/200/200', color: '#537AA1' },
  { id: 'cat-12', name: 'Soul', imageUrl: 'https://picsum.photos/seed/cat12/200/200', color: '#E8115B' },
];
